site_name: Nunte's 3DS Hacking Guide
site_url: https://3dsmanual.github.io/guide
extra_css:
  - style.css
nav:
  - Inicio: index.md
  - Comenzando:
    - Hackear la consola desde cero: comenzando.md
  - Información: info.md
